using AutoMapper;
using CodeFirst.Dtos;
using CodeFirst.Models;

namespace CodeFirst.Profiles
{
    public class UserProfile : Profile
    {
        public UserProfile()
        {
            CreateMap<UserToCreateDto, User>()
                .ForMember(dest => dest.Id, opt => opt.Ignore()) // Ignore Id (generated by DB)
                .ForMember(dest => dest.PhoneNumber, opt => opt.Ignore()) // Initially null
                .ForMember(dest => dest.DateTime, opt => opt.MapFrom(_ => DateTime.Now)); // Auto-set current time

            CreateMap<User, UserWithSafeInfoDto>();

        }
    }
}
